// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// readEyelinkSamples
DataFrame readEyelinkSamples(CharacterVector cv, CharacterVector cvBegin, CharacterVector cvEnd);
RcppExport SEXP eyeread_readEyelinkSamples(SEXP cvSEXP, SEXP cvBeginSEXP, SEXP cvEndSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< CharacterVector >::type cv(cvSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type cvBegin(cvBeginSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type cvEnd(cvEndSEXP );
        DataFrame __result = readEyelinkSamples(cv, cvBegin, cvEnd);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// readEyelinkMessages
DataFrame readEyelinkMessages(CharacterVector cv, CharacterVector cvBegin, CharacterVector cvEnd);
RcppExport SEXP eyeread_readEyelinkMessages(SEXP cvSEXP, SEXP cvBeginSEXP, SEXP cvEndSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< CharacterVector >::type cv(cvSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type cvBegin(cvBeginSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type cvEnd(cvEndSEXP );
        DataFrame __result = readEyelinkMessages(cv, cvBegin, cvEnd);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// readTrialDelimiters
DataFrame readTrialDelimiters(CharacterVector cvFname, CharacterVector cvBegin, CharacterVector cvEnd);
RcppExport SEXP eyeread_readTrialDelimiters(SEXP cvFnameSEXP, SEXP cvBeginSEXP, SEXP cvEndSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< CharacterVector >::type cvFname(cvFnameSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type cvBegin(cvBeginSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type cvEnd(cvEndSEXP );
        DataFrame __result = readTrialDelimiters(cvFname, cvBegin, cvEnd);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// readEyelinkTrials
DataFrame readEyelinkTrials(IntegerVector trials, CharacterVector cv, CharacterVector cvBegin, CharacterVector cvEnd);
RcppExport SEXP eyeread_readEyelinkTrials(SEXP trialsSEXP, SEXP cvSEXP, SEXP cvBeginSEXP, SEXP cvEndSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< IntegerVector >::type trials(trialsSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type cv(cvSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type cvBegin(cvBeginSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type cvEnd(cvEndSEXP );
        DataFrame __result = readEyelinkTrials(trials, cv, cvBegin, cvEnd);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
