# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

readEyelinkSamples <- function(cv, cvBegin, cvEnd) {
    .Call('eyeread_readEyelinkSamples', PACKAGE = 'eyeread', cv, cvBegin, cvEnd)
}

readEyelinkMessages <- function(cv, cvBegin, cvEnd) {
    .Call('eyeread_readEyelinkMessages', PACKAGE = 'eyeread', cv, cvBegin, cvEnd)
}

readTrialDelimiters <- function(cvFname, cvBegin, cvEnd) {
    .Call('eyeread_readTrialDelimiters', PACKAGE = 'eyeread', cvFname, cvBegin, cvEnd)
}

readEyelinkTrials <- function(trials, cv, cvBegin, cvEnd) {
    .Call('eyeread_readEyelinkTrials', PACKAGE = 'eyeread', trials, cv, cvBegin, cvEnd)
}

